# Generated by Django 5.0.12 on 2025-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='(123) 456-7890', max_length=20),
            preserve_default=False,
        ),
    ]
