# Generated by Django 5.0.12 on 2025-03-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunklogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunklog',
            old_name='camper_not_on_camp',
            new_name='not_on_camp',
        ),
    ]
