# Generated by Django 5.0.12 on 2025-03-08 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunklogs', '0002_rename_camper_not_on_camp_bunklog_not_on_camp'),
        ('campers', '0008_remove_camper_is_on_camp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bunklog',
            unique_together={('bunk_assignment', 'date')},
        ),
        migrations.AddField(
            model_name='bunklog',
            name='bunk_assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bunk_logs', to='campers.camperbunkassignment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bunklog',
            name='camper',
        ),
    ]
