# Generated by Django 5.0.12 on 2025-03-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0002_unit_bunk_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunk',
            name='unit',
        ),
    ]
