# Generated by Django 5.0.12 on 2025-03-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0003_remove_bunk_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunk',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bunks', to='bunks.unit'),
        ),
    ]
