# Generated by Django 5.0.12 on 2025-03-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0004_bunk_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunk',
            name='unit_head',
        ),
    ]
