# Generated by Django 5.0.12 on 2025-03-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0005_remove_bunk_unit_head'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bunk',
            unique_together={('cabin', 'session')},
        ),
        migrations.RemoveField(
            model_name='bunk',
            name='name',
        ),
    ]
