# Generated by Django 5.0.12 on 2025-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0006_alter_bunk_unique_together_remove_bunk_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunk',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
