# Generated by Django 5.0.12 on 2025-03-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bunks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('medical_notes', models.TextField(blank=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('is_on_camp', models.BooleanField(default=True)),
                ('status_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'camper',
                'verbose_name_plural': 'campers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CamperBunkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camper_assignments', to='bunks.bunk')),
                ('camper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunk_assignments', to='campers.camper')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bunks.session')),
            ],
            options={
                'verbose_name': 'camper bunk assignment',
                'verbose_name_plural': 'camper bunk assignments',
                'unique_together': {('camper', 'session')},
            },
        ),
    ]
