# Generated by Django 5.0.12 on 2025-03-03 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camperbunkassignment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='camperbunkassignment',
            name='start_date',
        ),
    ]
