# Generated by Django 5.0.12 on 2025-03-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunks', '0006_alter_bunk_unique_together_remove_bunk_name'),
        ('campers', '0002_remove_camperbunkassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camperbunkassignment',
            unique_together={('camper', 'bunk')},
        ),
        migrations.RemoveField(
            model_name='camperbunkassignment',
            name='session',
        ),
    ]
