# Generated by Django 5.0.12 on 2025-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0003_alter_camperbunkassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperbunkassignment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camperbunkassignment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
