# Generated by Django 5.0.12 on 2025-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0004_camperbunkassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperbunkassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camperbunkassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
