# Generated by Django 5.0.12 on 2025-03-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0005_alter_camperbunkassignment_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camper',
            old_name='dietary_restrictions',
            new_name='camper_notes',
        ),
        migrations.RenameField(
            model_name='camper',
            old_name='medical_notes',
            new_name='parent_notes',
        ),
    ]
