# Generated by Django 5.0.12 on 2025-03-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0006_rename_dietary_restrictions_camper_camper_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='camper',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
