# Generated by Django 5.0.12 on 2025-03-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0007_alter_camper_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camper',
            name='is_on_camp',
        ),
    ]
